from __future__ import annotations

from typing import Dict, List, Any

from .sample_data_factory_v5 import ParamInfo, ValueCandidate, suggest_values_for_param


def _choose_candidate(param: ParamInfo, selected: Dict[str, ValueCandidate]) -> ValueCandidate:
    cand = selected.get(param.name)
    if cand is not None:
        return cand
    cands = suggest_values_for_param(param)
    if not cands:
        return ValueCandidate(code="None", description="fallback", score=0.0)
    cands_sorted = sorted(cands, key=lambda c: (c.code == "None", -c.score))
    return cands_sorted[0]


def generate_sample_code(
    lib_name: str,
    node_row: Any,
    params: List[ParamInfo],
    selected_values: Dict[str, ValueCandidate],
) -> str:
    """選択された API からサンプル実行コードを生成する."""
    type_ = str(node_row.get("Type", "")).lower()
    path = str(node_row.get("Path", node_row.get("ID", "")))
    name = str(node_row.get("Name", "target"))
    origin_module = str(node_row.get("OriginModule", "") or "")
    flags = node_row.get("Flags")
    member_of = ""
    if isinstance(flags, dict):
        member_of = flags.get("member_of", "")

    chosen: Dict[str, ValueCandidate] = {}
    setup_lines: List[str] = []
    for p in params:
        cand = _choose_candidate(p, selected_values)
        chosen[p.name] = cand
        setup_lines.extend(cand.setup_lines)

    uniq_setup: List[str] = []
    seen = set()
    for line in setup_lines:
        if line not in seen:
            seen.add(line)
            uniq_setup.append(line)

    arg_exprs: List[str] = []
    for p in params:
        cand = chosen.get(p.name)
        if cand is None:
            continue
        if p.kind in ("VAR_POSITIONAL", "VAR_KEYWORD"):
            continue
        if cand.code:
            arg_exprs.append(f"{p.name}={cand.code}")
    args_str = ", ".join(arg_exprs)

    lines: List[str] = []
    lines.append("# -*- coding: utf-8 -*-")
    lines.append("# Sample code generated by Cognitive Library Explorer V5")
    lines.append(f"# Target: {path}")
    lines.append("")

    if uniq_setup:
        lines.extend(uniq_setup)
        lines.append("")

    if type_ == "function":
        if origin_module:
            lines.append(f"from {origin_module} import {name}")
            call_expr = f"{name}({args_str})" if args_str else f"{name}()"
        else:
            lines.append(f"import {lib_name}  # top-level に {name} が無い場合は path 側を参照してください")
            call_expr = f"{path}({args_str})" if args_str else f"{path}()"
    elif type_ in {"method", "property"}:
        if member_of:
            mod_name = member_of.rsplit(".", 1)[0]
            cls_name = member_of.split(".", 1)[-1]
        else:
            mod_name = origin_module or lib_name
            cls_name = "MyClass"
        if mod_name:
            lines.append(f"from {mod_name} import {cls_name}")
        else:
            lines.append("# TODO: import the appropriate class for this method")
        lines.append("")
        lines.append("# インスタンス生成（必要に応じて引数を調整してください）")
        lines.append(f"obj = {cls_name}()  # TODO: adjust constructor arguments if necessary")
        attr = name
        if type_ == "property":
            call_expr = f"obj.{attr}"
        else:
            call_expr = f"obj.{attr}({args_str})" if args_str else f"obj.{attr}()"
    elif type_ == "class":
        target_name = name or "TargetClass"
        if origin_module:
            lines.append(f"from {origin_module} import {target_name}")
        else:
            lines.append(f"from {lib_name} import {target_name}  # best effort import")
        call_expr = f"{target_name}({args_str})" if args_str else f"{target_name}()"
    else:
        lines.append("import importlib")
        if origin_module:
            lines.append(f"module = importlib.import_module('{origin_module}')")
            lines.append(f"target = getattr(module, '{name}')")
        else:
            lines.append(f"module = importlib.import_module('{lib_name}')")
            lines.append(f"target = getattr(module, '{name}', None)")
        call_expr = f"target({args_str})" if args_str else "target()"

    lines.append("")
    lines.append("if __name__ == '__main__':")
    lines.append(f"    result = {call_expr}")
    lines.append("    print('Result:', result)")
    return "\n".join(lines)
